code review !!!
alex-taxiera/ImageTagBot pull request #1
Opened 2018-12-12 02:40 UTC by GitStonic

2018-12-12 02:49 UTC, alex-taxiera requested changes
address all comments please

2018-12-12 02:49 UTC, alex-taxiera commented on config/settings.json
> +    "name": "just Tagger beta",
undo these

2018-12-12 02:49 UTC, alex-taxiera commented on package.json
> +    "nodemon": "^1.18.8"
nodemon does not need to be a dep

2018-12-12 02:49 UTC, alex-taxiera commented on src/commands/tag.js
> +const IMAGE_REGEXP = new RegExp(/^(https|http):?\/(.*).(png|jpeg|jpg|gif|PNG|JPEG|JPG|GIF)/)
why don't we just lowercase out strings before running the regex test?

2018-12-12 02:49 UTC, alex-taxiera commented on src/commands/tag.js
> +      console.log(tag)
remove this

2018-12-12 02:49 UTC, alex-taxiera commented on src/commands/tag.js
> +      const image = msg.attachments.length > 0 ? msg.attachments[0].url : url
this variable is still a url so src is a better name for it

2018-12-12 02:49 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +    this.tdbm = new TaggerDatabaseManager()
just use the instance from the tagger client, we don't need so many database managers

2018-12-12 02:49 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +  async upload (id, imgObj) {
imgObj can be called tag and have a key and a src like everywhere else

2018-12-12 02:49 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +    try {
don't need async await here we can just return the promise and use .then and .catch

2018-12-12 02:49 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +  async update (key, imgObj) {
same as previous func

2018-12-12 02:49 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +class ImgurClient {
maybe call it ImgurManager, client is not a good name

2018-12-12 02:49 UTC, alex-taxiera commented on src/commands/tag.js
> +        .catch((err) => {
leave it as error not err

2018-12-12 02:49 UTC, alex-taxiera commented on src/commands/tag.js
> +      let src = msg.attachments.length > 0 ? msg.attachments[0].url : url
why was this changed from a const?

2018-12-12 02:49 UTC, alex-taxiera commented on src/tagger/index.js
> +  generateString(length) {
what is this for?

2018-12-13 17:25 UTC, alex-taxiera submitted a review, later dismissed

2018-12-13 17:25 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +  handleTag (tag) {
better name for this function would be `upload` it can still take a Tag

2018-12-13 17:25 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +    imgur.setClientId(process.env.IMGUR_CLIENT_ID)
can we make imgur a property of the manager? like `this._api = imgur`

2018-12-13 17:25 UTC, alex-taxiera commented on src/commands/tag.js
> +          return `Tag \`${key}\` already exists`
check this before trying to upload to imgur

2018-12-13 17:25 UTC, alex-taxiera commented on src/commands/tag.js
> +      const result = await bot.imgur.handleTag({ key, src })
needs error handling

2018-12-13 17:25 UTC, alex-taxiera commented on src/commands/tag.js
> +          console.log(error)
errors should still return something to tell the user an error occured

2018-12-13 17:25 UTC, alex-taxiera commented on src/tagger/imgurClient.js
> +    this.bot = bot
doesn't appear like this class is using bot anymore

2018-12-15 17:01 UTC, GitStonic commented on src/commands/tag.js
> +          return `Tag \`${key}\` already exists`
wait what?

2018-12-15 17:04 UTC, alex-taxiera commented on src/commands/tag.js
> +          return `Tag \`${key}\` already exists`
I mean check to see if the tag is in the db before doing anything with imgur

2018-12-23 17:41 UTC, alex-taxiera approved these changes
👍

2018-12-23 17:42 UTC, merged